package:
  name: harold_packaging_example
  version: "0.1.6"

source:
  git_rev: v0.1.6
  git_url: https://github.com/HaroldMills/Python-Packaging-Example.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - harold_test = harold_test:main
    #
    # Would create an entry point called harold_test that calls harold_test.main()

    - test_script=harold_packaging_example.module:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyyaml

test:
  # Python imports
  imports:
    - harold_packaging_example
    - harold_packaging_example.util

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - test_script --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/HaroldMills/Python-Packaging-Example
  license: MIT
  license_file: LICENSE
  summary: 'Simple Python packaging example.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
